#' The initial flux of birds
#'
#' The flux of birds travelling through the turbine area
#' @param NTurbines An integer value. The number of turbines in the site.
#' @param sampledBirdParams A data frame. The data frame with all the sampled parameters of the bird's features
#' @param sampledTurbine A data frame. The data frame with all the sampled parameters from the turbine
#' @param sampledSpeciesCount A data frame. The sample of the density of birds in the wind farm area (i.e. the count)
#' @param TPower An integer. The total approximate power meant to be generated by the wind farm (TurbineModel field)
#' @param hours A data frame. The total number of hours per day at the latitude calculated by DayLength()
#' @return A data frame. The hours data frame returned with the flux calculations included
#' @export

initial_flux <- function(NTurbines=NTurbines,
                         sampledTurbine=sampledTurbine,
                         sampledBirdParams=sampledBirdParams,
                         sampledSpeciesCount=sampledSpeciesCount,
                         TPower=TPower,
                         hours=hours){

  TotalFrontalArea = NTurbines * pi * sampledTurbine$RotorRadius ^2
  #### Calculate the total number of birds passing through the wind farm in each month
  for (h in 1:nrow(hours)) {
    hours$Flux[h] = sampledBirdParams$FlightSpeed * sampledSpeciesCount[, h]/ (2 * sampledTurbine$RotorRadius) * TotalFrontalArea *
      (hours$Day[h] + sampledBirdParams$NocturnalActivity * hours$Night[h]) * 3600/1000000
  }
  return(hours)
}

